version: '3.9'

services:
  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker_server_1
    ports:
      - "6001:6000"
    networks:
      - app_network

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker_server_2
    ports:
      - "6002:6000"
    networks:
      - app_network

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker_server_3
    ports:
      - "6003:6000"
    networks:
      - app_network

  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: master_server
    ports:
      - "5001:5001"
    networks:
      - app_network
    depends_on:
      - worker1
      - worker2
      - worker3

networks:
  app_network:
    driver: bridge
